version: 2.1
jobs:
  build:
      docker:
          - image: circleci/node:12.13.0
      steps:
        - checkout
        - run: npm install
test:
  executor: windows/default
  steps:
    - checkout
    - run: npm test
    - store_artifacts:
        path: ./test-results
        destination: test-results
    - store_test_results:
        path: ./test-results
        